import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Demo',
      items: [{type: 'autogenerated', dirName: 'demo'}],
    },
    {
      type: 'category',
      label: 'Platform',
      items: [{type: 'autogenerated', dirName: 'platform'}],
    },
    {
      type: 'category',
      label: 'Features',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Docusaurus Tutorial (Upstream)',
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],
};

export default sidebars;
