name: deploy-docs
on:
  push:
    branches:
      - main
      - "*.*.*"

jobs:
  deploy:
    uses: Ascertia-Integrations/docusaurus-github-pages-poc/.github/workflows/reusable-deploy-docs.yml@v0.1.0
    secrets: inherit
    permissions:
      contents: write
      pages: write
      id-token: write
